# Site settings
title: ccvk.me
email: claudiacv22@gmail.com
description: "Claudia Vargas El Khatib UX design research psychology" #> # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ccvk.me" # the base hostname & protocol for your site
twitter_username: claucvk
github_username: claucvk

# Build settings
markdown: kramdown
