# Site settings
title: Claudia Vargas
header-img: img/home-bg.jpg
email: claudiacv22@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://claucvk.github.io"
twitter_username:
github_username:  claucvk
facebook_username: ClauKV

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
